Blogs/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blogs.Models;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace Blogs.Controllers
{
    public class BlogsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blogs
        //[Authorize]
        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        // GET: Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blogs/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "BlogID,Heading,Category,Tag,Content,ImagePath,User")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                var user_id = Convert.ToString(blog.User);
                user_id = System.Web.HttpContext.Current.User.Identity.Name.ToString();
                db.Blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blog);
        }

        // GET: Blogs/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlogID,Heading,Category,Tag,Content,ImagePath,FileName,CreationDate")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpPost]
        public ActionResult FileUpload(Blog model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string pic = Guid.NewGuid().ToString() + Path.GetFileName(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/Images/"), pic);
                    file.SaveAs(path);
                    model.ImagePath = "/Images/" + (file.FileName);
                }

                model.CreationDate = DateTime.Now;
                String user_id = System.Web.HttpContext.Current.User.Identity.Name.ToString();
                model.User = db.Users.FirstOrDefault(
                        x => x.UserName == user_id);
                db.Blogs.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Create", model);

        }
        }
    }

Blogs/Controllers/CSharpController.cs
using Blogs.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogs.Controllers
{
    public class CSharpController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            List<Blog> blogs = db.Blogs.Where(a => a.Category == "C#").OrderByDescending(a => a.CreationDate).ToList();
            return View(blogs);
        }

        public ActionResult HP()
        {
            List<Blog> blogs = db.Blogs.Where(a => a.Category == "C#").OrderByDescending(a => a.CreationDate).ToList();
            return View(blogs);
        }
    }
}

Blogs/Controllers/HomeController.cs
using Blogs.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogs.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            List<Blog> Blogs = db.Blogs.OrderByDescending(b => b.CreationDate).Take(5).ToList();            return View(Blogs);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Blogs/Controllers/MVCNetController.cs
using Blogs.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogs.Controllers
{
    public class MVCNetController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            List<Blog> blogs = db.Blogs.Where(a => a.Category == "MVC.Net").OrderByDescending(a => a.CreationDate).ToList();
            return View(blogs);
        }

        public ActionResult HP()
        {
            List<Blog> blogs = db.Blogs.Where(a => a.Category == "MVC.Net").OrderByDescending(a => a.CreationDate).ToList();
            return View(blogs);
        }
    }
}

Blogs/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Blogs/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Blogs/Views/Home/Index.cshtml
@using Blogs.Models;
@model IEnumerable<Blog>
@{
    ViewBag.Title = "Home Page";
}


@section styles {
    <link href="~/slippry-1.4.0/dist/slippry.css" rel="stylesheet" />
    <style type="text/css">
        /* News */
        .news-slider {
        }

            .news-slider .text-content {
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                background-color: rgba(255,255,255,0.9);
                padding: 1em;
                width: 30%;
                height: 100%;
            }

                .news-slider .text-content h4 {
                    margin: 0;
                    text-align: center;
                }

                .news-slider .text-content p {
                    margin: 1em 0;
                }

                .news-slider .text-content a.button-link {
                    padding: 0.25em 0.5em;
                    position: absolute;
                    bottom: 1em;
                    right: 1em;
                }

            .news-slider .image-content {
                line-height: 0;
            }

                .news-slider .image-content img {
                    max-width: 100%;
                }

            .news-slider .news-pager {
                text-align: right;
                display: block;
                margin: 0.2em 0 0;
                padding: 0;
                list-style: none;
            }

                .news-slider .news-pager li {
                    display: inline-block;
                    padding: 0.6em;
                    margin: 0 0 0 1em;
                }

                    .news-slider .news-pager li.sy-active a {
                        color: #31ace2;
                    }

                    .news-slider .news-pager li a {
                        font-weight: 500;
                        text-decoration: none;
                        display: block;
                        color: #222;
                    }
    </style>
}
<section id="news-demo">
    @foreach (Blog b in Model)
    {
        <article>
            <div class="text-content">
                <h4>@Html.ActionLink(@b.Heading, "Details", "Blogs", new { id = @b.BlogID }, new { style = "color: black" })</h4>
                <a href="@Url.Action("Details","Blogs", new { id = @b.BlogID })" class="button-link read-more">read more</a>
            </div>
            <div class="image-content"><a href="@Url.Action("Details","Blogs", new { id = @b.BlogID })"><img src="@b.ImagePath" alt="BlogImage"></a></div>
        </article>
    }
</section>
@section scripts {
    <script src="~/slippry-1.4.0/dist/slippry.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery('#news-demo').slippry({
                // general elements & wrapper
                slippryWrapper: '<div class="sy-box news-slider" />', // wrapper to wrap everything, including pager
                elements: 'article', // elments cointaining slide content

                // options
                adaptiveHeight: false, // height of the sliders adapts to current
                captions: false,

                // pager
                pagerClass: 'news-pager',

                // transitions
                transition: 'horizontal', // fade, horizontal, kenburns, false
                speed: 1200,
                pause: 8000,

                // slideshow
                autoDirection: 'prev'
            });
        });
    </script>
}

<div class="row">
    <div class="col-md-6" style="background-color:lightblue">
        <h2>@Html.ActionLink("C#", "Index", "CSharp", null, new { style = "color: black" })</h2> @{Html.RenderAction("HP", "CSharp"); }
    </div>

    <div class="col-md-6" style="background-color:coral">
        <h2>@Html.ActionLink("MVC.Net", "Index", "MVCNet", null, new { style = "color: black" })</h2> @{ Html.RenderAction("HP", "JavaScript"); }
    </div>

    <div class="col-md-6" style="background-color:khaki">
        <h2>@Html.ActionLink("JavaScript", "Index", "JavaScript", null, new { style = "color: black" })</h2> 
        @{ Html.RenderAction("HP", "JavaScript"); }
    </div>


    <div class="col-md-6" style="background-color:darkgray">
        <h2>@Html.ActionLink("CSS", "Index", "CSS", null, new { style = "color: black" })</h2> @{ Html.RenderAction("HP", "CSS"); }
    </div>
</div>